apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-depl
  template:
    metadata:
      labels:
        app: tickets-depl
    spec:
      containers:
        - name: tickets
          image: chikkipikki/tickets
          env:
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-srv:27017/tickets"
            - name: JWT_KEY #name as it shows up inside of the container
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  type: ClusterIP
  selector:
    app: tickets-depl
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
